import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/About.module.css";
import Link from "next/link";
import Restrainer from "@/components/Restrainer";
import MainNav from '@/components/MainNav'


export default function Home() {
  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Restrainer>
          <main className={styles.main}>
            <MainNav />
            <div className={styles.container}>
              <h1 className={styles.h1}>OUR TEAM</h1>
              <Image className={styles.line} src="/image 4.png" alt="Line" width={350} height={400} />
              <div className={styles.jillian}>
                  <Image className={styles.cat} src="/506.png" alt="Cat Drawing" width={130} height={220} />
                  <div className={styles.jillianDescContainer}>
                      <h1 className={styles.jillianText}>Jillian G.</h1>
                      <p className={styles.jillianDesc}>ux/ui designer</p>
                  </div>
              </div>
              <div className={styles.characteristicsContainer}>
              <p className={styles.characteristics}>#detail-oriented #creative #adaptable</p>
              </div>
              <div className={styles.celine}>
                  <div className={styles.celineDescContainer}>
                      <h1 className={styles.celineText}>Celine W.</h1>
                      <p className={styles.celineDesc}>ux/ui designer</p>
                  </div>
                  <Image className={styles.dog} src="/942.png" alt="Dog Drawing" width={95} height={300} />
              </div>
              <div className={styles.celinecharacteristicsContainer}>
              <p className={styles.celinecharacteristics}>#artistic #eager-to-learn #team-player</p>
              </div>
              <Image className={styles.line} src="/image 4.png" alt="Line" width={350} height={400} />
            </div>
          </main>
      </Restrainer>
    </>
  )
}
