import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/About.module.css";
import Link from "next/link";
import Restrainer from "@/components/Restrainer";
import MainNav from '@/components/MainNav'


export default function About() {
  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Restrainer>
          <main className={styles.main}>
            <MainNav />
            <div className={styles.container}>
              <div className={styles.topContainer}>
                <h1 className={styles.h1}>RESOURCES</h1>
                <Image className={styles.line} src="/image 4.png" alt="Line" width={160} height={400} />
              </div>
              
              <Image className={styles.line} src="/image 4.png" alt="Line" width={160} height={400} />
            </div>
          </main>
      </Restrainer>
    </>
  )
}
