import Head from "next/head";
import Image from "next/image";
import Restrainer from "@/components/Restrainer";
import IntroductionTemplate from "@/components/IntroductionTemplate";
import PieChart from "@/components/PieChart";
import { useRouter } from "next/router";
import heart from "@/public/1347 1 (1).png"

export default function Introduction() {

  const router = useRouter()

  const introImageSrcValue = (res) => {
    switch(res) {
        case "1" :
            return (
              <Image style={{height: "auto"}}
              src={heart}
              alt="heart"
              width={80} 
              height={200} />
            )
        break
        case "2" :
            return (<PieChart />)
        break
        case "3" :
          return (
            <Image style={{height: "auto"}}
            src={heart}
            alt="heart"
            width={80} 
            height={200} />
          )
        break
    }
}

    const introDescription = (res) => {
      switch(res) {
          case "1" :
              return "Wonderland is an app inspired by \"Alice in Wonderland\" that assesses personality types with an immersive quiz, promoting self-discovery and mental health reflection."
          break
          case "2" :
              return "Wonderland helps uncover users' strengths to combat procrastination, offering support for both occasional and chronic cases."
          break
          case "3" :
              return "Wonderland aids with daily challenges but is not a substitute for professional help. Chronic procrastination can signal conditions like ADHD, depression, or anxiety. If procrastination hampers daily tasks, it may be indicating potential underlying issues. Consider reaching out to a mental health professional for support."
          break
      }
    }

  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <IntroductionTemplate
          introImageSrc={introImageSrcValue(router.query.intro)}
          description={introDescription(router.query.intro)}
        />
    </>
  )
}

