import Head from "next/head";
import Image from "next/image";
import styles from "./Introduction.module.css";
import Link from "next/link";
import Restrainer from "@/components/Restrainer";
import MainNav from "@/components/MainNav";


export default function Home() {
  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Restrainer>
        <main className={`${styles.main}`}>
          <div className={styles.textContainer}>
            <Image className={styles.topText} src="/top.png" alt="wonderlandtext" width={340} height={370} />
          </div>
          <div className={styles.borderContainer}>
            <Image className={styles.border} src="/image 25.png" alt="Logo" width={400} height={200} />
          </div>
          <div className={styles.descriptionImageContainer}>
            <Image className={styles.descriptionImage} src="/mental-health 1.png" alt="brain-vector" width={75} height={200} />
          </div>
          <div className={styles.descriptionTextContainer}>
            <p className={styles.descriptionText}>Wonderland is an innovative app <br />
                crafted to dive into users’ mental <br />
                well-being in an interactive and <br />
                engaging manner. Drawing inspiration <br />
                from ‘Alice in Wonderland,’ this app <br />
                seeks to evaluate users’ burnout <br />
                levels through an immersive and <br />
                playful quiz. By incorporating elements <br />
                from the beloved story line of Alice, <br />
                our aim is to take our users into <br />
                a similar journey where they can learn <br />
                more about themselves and <br />
                reflect upon their mental health.</p>
          </div>
          
        </main>
      </Restrainer>
    </>
  )
}

