import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Journey.module.css";
import Restrainer from "@/components/Restrainer";
import { useRouter } from "next/router";


export default function Journey() {

    const router = useRouter()

    const handleClick = () => {
        router.push("/main")
    }

  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Restrainer>
          <main className={styles.main}>
            <div className={styles.clickOverlay} onClick={handleClick}></div>
            <div className={styles.cardKing}>
              <Image src="/king 1.png" alt="King Card" width={50} height={50} />
            </div>
              <div className={styles.container}>
                <div className={styles.firstTextContainer}>
                    <p className={styles.firstText}>Wonderland is an innovative app crafted to dive into users’ mental well-being in an interactive and engaging manner. Drawing inspiration from ‘Alice in Wonderland,’ this appseeks to evaluate users’ burnout levels through an immersive and playful quiz. By incorporating elements from the beloved story line of Alice, our aim is to take our users into a similar journey where they can learn more about themselves and reflect upon their mental health.</p>
                </div>
                <div className={styles.secondTextContainer}>
                    <p className={styles.firstText}>Wonderland is an innovative app crafted to dive into users’ mental well-being in an interactive and engaging manner. Drawing inspiration from ‘Alice in Wonderland,’ this appseeks to evaluate users’ burnout levels through an immersive and playful quiz. By incorporating elements from the beloved story line of Alice, our aim is to take our users into a similar journey where they can learn more about themselves and reflect upon their mental health.</p>
                    <Image className={styles.cardQueen} src="/person.png" alt="Queen Card" width={70} height={70} />
                </div>
                <div className={styles.thirdTextContainer}>
                    <p className={styles.firstText}>Click Anywhere To Start</p>
                </div>
              </div>
              <div className={styles.cardQueen}>
                <Image src="/queen 1.png" alt="Queen Card" width={50} height={50} />
              </div>
          </main>
      </Restrainer>
    </>
  )
}
