import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Journey.module.css";
import Restrainer from "@/components/Restrainer";
import { useRouter } from "next/router";


export default function Journey() {

    const router = useRouter()

    const handleClick = () => {
        router.push("/main")
    }

  return (
    <>
      <Head>
        <title>Wonderland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Restrainer>
          <main className={styles.main}>
            <div className={styles.clickOverlay} onClick={handleClick}></div>
            <div className={styles.cardKing}>
              <Image src="/king 1.png" alt="King Card" width={65} height={65} />
            </div>
              <div className={styles.container}>
                <div className={styles.firstTextContainer}>
                    <p className={styles.firstText}>Wonderland is an innovative app designed to dive into users' well-being, fostering reflection and personal growth in an interactive, engaging way.</p>
                </div>
                <div className={styles.secondTextContainer}>
                    <p className={styles.firstText}>You will be guided to a page that offers features to aid relaxation and self-discovery within our app. Dive in and explore with Alice as your guide!</p>
                    <Image className={styles.alice} src="/Rectangle 33.png" alt="Alice" width={200} height={70} />
                </div>
                <div className={styles.thirdTextContainer}>
                    <p className={styles.firstText}>Click Anywhere To Start</p>
                </div>
              </div>
              <div className={styles.cardQueen}>
                <Image src="/queen 1.png" alt="Queen Card" width={65} height={65} />
              </div>
          </main>
      </Restrainer>
    </>
  )
}
